/**
 * InstantStudy's 16-language locale catalog.
 * This first expansion translates key controls and navigation. Untranslated
 * explanatory copy falls back to vetted English until native review.
 */

const coreKeys=["language","home","library","create","guide","flashcards","learn","test","ask","review","friends","insights","podcast","studyGame","family","loading","start","submitAnswer","typeAnswer","questions","time","complete","reveal","recall","studyMode","yourMaterial","playPodcast","stopPodcast","learnAnything"] as const;
const compact: Record<string, readonly string[]> = {
  "nl": [
    "Taal",
    "Home",
    "Bibliotheek",
    "Maken",
    "Studiegids",
    "Flashcards",
    "Leren",
    "Oefentoets",
    "Vragen",
    "Herhalen",
    "Samen studeren",
    "Inzichten",
    "Podcast",
    "Studiegame",
    "Familie",
    "Laden…",
    "Starten",
    "Antwoord indienen",
    "Typ je antwoord…",
    "Vragen",
    "Tijd",
    "Voltooid",
    "Tonen",
    "Ophalen",
    "STUDIEMODUS",
    "JOUW MATERIAAL",
    "Podcast afspelen",
    "Podcast stoppen",
    "Leer van\nalles."
  ],
  "fr": [
    "Langue",
    "Accueil",
    "Bibliothèque",
    "Créer",
    "Guide d’étude",
    "Fiches",
    "Apprendre",
    "Examen blanc",
    "Demander",
    "Réviser",
    "Étudier ensemble",
    "Analyses",
    "Podcast",
    "Jeu d’étude",
    "Famille",
    "Chargement…",
    "Commencer",
    "Envoyer la réponse",
    "Saisissez votre réponse…",
    "Questions",
    "Temps",
    "Terminé",
    "Révéler",
    "Se rappeler",
    "MODE D’ÉTUDE",
    "VOTRE CONTENU",
    "Lire le podcast",
    "Arrêter le podcast",
    "Apprenez avec\ntout."
  ],
  "de": [
    "Sprache",
    "Startseite",
    "Bibliothek",
    "Erstellen",
    "Lernleitfaden",
    "Karteikarten",
    "Lernen",
    "Probetest",
    "Fragen",
    "Wiederholen",
    "Gemeinsam lernen",
    "Einblicke",
    "Podcast",
    "Lernspiel",
    "Familie",
    "Lädt…",
    "Starten",
    "Antwort senden",
    "Antwort eingeben…",
    "Fragen",
    "Zeit",
    "Abgeschlossen",
    "Aufdecken",
    "Erinnern",
    "LERNMODUS",
    "DEIN MATERIAL",
    "Podcast abspielen",
    "Podcast stoppen",
    "Lerne mit\nallem."
  ],
  "id": [
    "Bahasa",
    "Beranda",
    "Perpustakaan",
    "Buat",
    "Panduan Belajar",
    "Kartu Flash",
    "Belajar",
    "Tes Latihan",
    "Tanya",
    "Ulangi",
    "Belajar Bersama",
    "Wawasan",
    "Podcast",
    "Permainan Belajar",
    "Keluarga",
    "Memuat…",
    "Mulai",
    "Kirim jawaban",
    "Ketik jawabanmu…",
    "Pertanyaan",
    "Waktu",
    "Selesai",
    "Tampilkan",
    "Ingat kembali",
    "MODE BELAJAR",
    "MATERIMU",
    "Putar podcast",
    "Hentikan podcast",
    "Belajar dari\napa saja."
  ],
  "it": [
    "Lingua",
    "Home",
    "Libreria",
    "Crea",
    "Guida allo studio",
    "Flashcard",
    "Impara",
    "Test di prova",
    "Chiedi",
    "Ripassa",
    "Studia con gli amici",
    "Statistiche",
    "Podcast",
    "Gioco di studio",
    "Famiglia",
    "Caricamento…",
    "Inizia",
    "Invia risposta",
    "Scrivi la tua risposta…",
    "Domande",
    "Tempo",
    "Completato",
    "Mostra",
    "Ricorda",
    "MODALITÀ STUDIO",
    "IL TUO MATERIALE",
    "Riproduci podcast",
    "Ferma podcast",
    "Impara da\nqualsiasi cosa."
  ],
  "ja": [
    "言語",
    "ホーム",
    "ライブラリ",
    "作成",
    "学習ガイド",
    "単語カード",
    "学習",
    "模擬テスト",
    "質問",
    "復習",
    "友達と学ぶ",
    "学習分析",
    "ポッドキャスト",
    "学習ゲーム",
    "ファミリー",
    "読み込み中…",
    "開始",
    "回答を送信",
    "回答を入力…",
    "問題",
    "時間",
    "完了",
    "表示",
    "思い出す",
    "学習モード",
    "学習教材",
    "再生",
    "停止",
    "あらゆる教材で\n学ぼう。"
  ],
  "ko": [
    "언어",
    "홈",
    "라이브러리",
    "만들기",
    "학습 가이드",
    "플래시카드",
    "학습",
    "모의시험",
    "질문",
    "복습",
    "친구와 공부",
    "학습 분석",
    "팟캐스트",
    "학습 게임",
    "가족",
    "불러오는 중…",
    "시작",
    "답변 제출",
    "답변을 입력하세요…",
    "문제",
    "시간",
    "완료",
    "공개",
    "기억해 보기",
    "학습 모드",
    "내 학습 자료",
    "팟캐스트 재생",
    "팟캐스트 정지",
    "어떤 자료로든\n학습하세요."
  ],
  "pl": [
    "Język",
    "Strona główna",
    "Biblioteka",
    "Utwórz",
    "Przewodnik do nauki",
    "Fiszki",
    "Ucz się",
    "Test próbny",
    "Zapytaj",
    "Powtórz",
    "Ucz się z innymi",
    "Statystyki",
    "Podcast",
    "Gra edukacyjna",
    "Rodzina",
    "Ładowanie…",
    "Rozpocznij",
    "Wyślij odpowiedź",
    "Wpisz odpowiedź…",
    "Pytania",
    "Czas",
    "Ukończono",
    "Odkryj",
    "Przypomnij sobie",
    "TRYB NAUKI",
    "TWOJE MATERIAŁY",
    "Odtwórz podcast",
    "Zatrzymaj podcast",
    "Ucz się z\ndowolnych materiałów."
  ],
  "ru": [
    "Язык",
    "Главная",
    "Библиотека",
    "Создать",
    "Учебное пособие",
    "Карточки",
    "Учиться",
    "Пробный тест",
    "Спросить",
    "Повторить",
    "Учиться вместе",
    "Аналитика",
    "Подкаст",
    "Учебная игра",
    "Семья",
    "Загрузка…",
    "Начать",
    "Отправить ответ",
    "Введите ответ…",
    "Вопросы",
    "Время",
    "Готово",
    "Показать",
    "Вспомнить",
    "РЕЖИМ ОБУЧЕНИЯ",
    "ВАШИ МАТЕРИАЛЫ",
    "Включить подкаст",
    "Остановить подкаст",
    "Учитесь на\nлюбых материалах."
  ],
  "zh-CN": [
    "语言",
    "首页",
    "资料库",
    "创建",
    "学习指南",
    "闪卡",
    "学习",
    "模拟测试",
    "提问",
    "复习",
    "与朋友共学",
    "学习分析",
    "播客",
    "学习游戏",
    "家庭",
    "加载中…",
    "开始",
    "提交答案",
    "输入你的答案…",
    "题目",
    "时间",
    "完成",
    "显示",
    "回忆",
    "学习模式",
    "你的学习资料",
    "播放播客",
    "停止播客",
    "用任何资料\n开始学习。"
  ],
  "es": [
    "Idioma",
    "Inicio",
    "Biblioteca",
    "Crear",
    "Guía de estudio",
    "Tarjetas",
    "Aprender",
    "Examen de práctica",
    "Preguntar",
    "Repasar",
    "Estudiar juntos",
    "Estadísticas",
    "Podcast",
    "Juego de estudio",
    "Familia",
    "Cargando…",
    "Comenzar",
    "Enviar respuesta",
    "Escribe tu respuesta…",
    "Preguntas",
    "Tiempo",
    "Completado",
    "Mostrar",
    "Recordar",
    "MODO DE ESTUDIO",
    "TU MATERIAL",
    "Reproducir podcast",
    "Detener podcast",
    "Aprende con\ncualquier material."
  ],
  "tr": [
    "Dil",
    "Ana sayfa",
    "Kütüphane",
    "Oluştur",
    "Çalışma rehberi",
    "Bilgi kartları",
    "Öğren",
    "Deneme sınavı",
    "Sor",
    "Tekrar et",
    "Birlikte çalış",
    "İstatistikler",
    "Podcast",
    "Çalışma oyunu",
    "Aile",
    "Yükleniyor…",
    "Başla",
    "Yanıtı gönder",
    "Yanıtını yaz…",
    "Sorular",
    "Süre",
    "Tamamlandı",
    "Göster",
    "Hatırla",
    "ÇALIŞMA MODU",
    "ÇALIŞMA MATERYALİN",
    "Podcast'i oynat",
    "Podcast'i durdur",
    "Her materyalden\nöğren."
  ],
  "uk": [
    "Мова",
    "Головна",
    "Бібліотека",
    "Створити",
    "Навчальний посібник",
    "Картки",
    "Навчатися",
    "Пробний тест",
    "Запитати",
    "Повторити",
    "Навчатися разом",
    "Аналітика",
    "Подкаст",
    "Навчальна гра",
    "Родина",
    "Завантаження…",
    "Почати",
    "Надіслати відповідь",
    "Введіть відповідь…",
    "Питання",
    "Час",
    "Завершено",
    "Показати",
    "Пригадати",
    "РЕЖИМ НАВЧАННЯ",
    "ВАШІ МАТЕРІАЛИ",
    "Відтворити подкаст",
    "Зупинити подкаст",
    "Навчайтеся з\nбудь-яких матеріалів."
  ],
  "vi": [
    "Ngôn ngữ",
    "Trang chủ",
    "Thư viện",
    "Tạo",
    "Hướng dẫn học",
    "Thẻ ghi nhớ",
    "Học",
    "Bài kiểm tra thử",
    "Hỏi",
    "Ôn tập",
    "Học cùng bạn bè",
    "Thống kê",
    "Podcast",
    "Trò chơi học tập",
    "Gia đình",
    "Đang tải…",
    "Bắt đầu",
    "Gửi câu trả lời",
    "Nhập câu trả lời…",
    "Câu hỏi",
    "Thời gian",
    "Hoàn thành",
    "Hiển thị",
    "Gợi nhớ",
    "CHẾ ĐỘ HỌC",
    "TÀI LIỆU CỦA BẠN",
    "Phát podcast",
    "Dừng podcast",
    "Học từ\nmọi tài liệu."
  ]
};
export const localePacks: Record<string,{ translation: Record<string,Record<string,string>> }> =
  Object.fromEntries(Object.entries(compact).map(([locale,values])=>{
    const entries=Object.fromEntries(coreKeys.map((key,index)=>[key,values[index]]));
    return [locale,{translation:{
      common:Object.fromEntries(["language","home","library","create","guide","flashcards","learn","test","ask","review","friends","insights","podcast","studyGame","family","loading"].map(key=>[key,entries[key]])),
      software:{
        startLearn:entries.start,submitAnswer:entries.submitAnswer,
        typeAnswer:entries.typeAnswer,questions:entries.questions,
        playPodcast:entries.playPodcast,stopPodcast:entries.stopPodcast,
        mastery:entries.insights,
      },
      landing:{openSoftware:entries.start,heroTitle:entries.learnAnything.replace("\n"," ")}
    }}];
  }));
